include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    unawaited_futures: error
    unrelated_type_equality_checks: error
    avoid_relative_lib_imports: error
    always_use_package_imports: warning
linter:
  rules:
    depend_on_referenced_packages: false
    overridden_fields: false
    constant_identifier_names: false
    non_constant_identifier_names: false
    curly_braces_in_flow_control_structures: false
    unawaited_futures: true
    always_declare_return_types: true
    avoid_void_async: true
    avoid_redundant_argument_values : true
    avoid_unnecessary_containers: true
    sort_constructors_first : true
    avoid_relative_lib_imports: true
    always_use_package_imports: true
    prefer_const_constructors: true
    prefer_final_fields: true

